### ISSUE TITLE
Numbered classes in attribute selectors are ignored - Mailchimp

### ISSUE THREAD

**Issue by ivandurst** [Omgitsonlyalex/Crowder-Email-Template#1]
Today I noticed a mailchimp issue that caused some of your classes to be ignored. When you use attribute selectors in Mailchimp, such as 

``` CSS
*[class="100p"] {
  width: 100% !important;
  height: auto !important;
}
```

Mailchimp strips out the quotes, so you're left with `*[class=100p]`. Attribute selectors that begin with numbers and aren't quoted are invalid, and are ignored. Just a heads up, as I've also seen these class names in a Litmus article about "how to build an email from scratch," and this will baffle any newer developers working with Mailchimp.
